// crates/protocol-java/src/main.rs

//! Generates the Java message types of the node protocol.
//!
//! The application side of the protocol is Java. Its types come from the
//! same description as the Rust ones (`protocol/node-protocol.schema.json`),
//! so the two sides cannot be written apart. The types generated here are
//! carriers: what is accepted is decided by the description, which the Java
//! side checks a message against before it becomes one of these types —
//! exactly as the Rust side does.
//!
//! The generator understands the forms the description uses and refuses any
//! other: a form it would have to guess at stops the generation, with the
//! definition named.
//!
//! Next to the generated types the generator places the hand-written part of
//! the library (`java/` of this repository) and the description itself, so
//! that the output directory is the whole library.
//!
//! Usage: `protocol-java <description.json> <java.package> <output-dir>`

use std::{
    collections::BTreeSet,
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
    process::ExitCode,
};

use serde_json::{Map, Value};

type Generated<T> = Result<T, String>;

const DESCRIPTION_NAME: &str = "node-protocol.schema.json";

/// Words a Java record component cannot be named.
const JAVA_RESERVED: &[&str] = &[
    "abstract",
    "assert",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extends",
    "final",
    "finally",
    "float",
    "for",
    "goto",
    "if",
    "implements",
    "import",
    "instanceof",
    "int",
    "interface",
    "long",
    "native",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "record",
    "return",
    "sealed",
    "short",
    "static",
    "strictfp",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "true",
    "false",
    "try",
    "var",
    "void",
    "volatile",
    "while",
    "yield",
];

fn main() -> ExitCode {
    match run() {
        Ok(count) => {
            println!("generated {count} Java files");
            ExitCode::SUCCESS
        }
        Err(problem) => {
            eprintln!("protocol-java: {problem}");
            ExitCode::FAILURE
        }
    }
}

#[expect(
    clippy::disallowed_methods,
    reason = "reads the protocol description of this repository, not a message"
)]
fn run() -> Generated<usize> {
    let arguments: Vec<String> = env::args().skip(1).collect();
    let [description_path, package, output] = arguments.as_slice() else {
        return Err("usage: protocol-java <description.json> <java.package> <output-dir>".into());
    };

    let text = fs::read_to_string(description_path)
        .map_err(|error| format!("cannot read {description_path}: {error}"))?;
    let description: Value =
        serde_json::from_str(&text).map_err(|error| format!("{description_path}: {error}"))?;
    let definitions = description
        .get("definitions")
        .and_then(Value::as_object)
        .ok_or("the description has no definitions")?;

    let directory = package
        .split('.')
        .fold(PathBuf::from(output), |path, part| path.join(part));
    fs::create_dir_all(&directory).map_err(|error| format!("{}: {error}", directory.display()))?;

    let mut written = BTreeSet::new();
    for (name, definition) in definitions {
        let body = declaration(name, definition, package)
            .map_err(|problem| format!("{name}: {problem}"))?;
        write_file(&directory, package, name, &body)?;
        written.insert(name.clone());
    }

    // The hand-written part of the library travels with the generated one,
    // in the same package: the checked decoding and the audio frames.
    for (name, source) in HAND_WRITTEN {
        if written.contains(*name) {
            return Err(format!(
                "{name}: a definition has the name of a hand-written class"
            ));
        }
        let path = directory.join(format!("{name}.java"));
        fs::write(&path, in_package(source, package)?)
            .map_err(|error| format!("{}: {error}", path.display()))?;
        written.insert((*name).to_owned());
    }

    let package_info = format!(
        "// Generated by protocol-java. Do not edit.\n\
         /**\n * Messages of the Gabion node protocol: the types generated from the protocol description,\n \
         * the checked decoding ({{@link {package}.ProtocolJson}}) and the audio frames\n \
         * ({{@link {package}.AudioFrame}}).\n */\n\
         @NullMarked\npackage {package};\n\nimport org.jspecify.annotations.NullMarked;\n"
    );
    fs::write(directory.join("package-info.java"), package_info)
        .map_err(|error| format!("package-info.java: {error}"))?;

    // The description itself is a resource of the library: the checked
    // decoding reads it from next to its own class.
    fs::write(directory.join(DESCRIPTION_NAME), &text)
        .map_err(|error| format!("{DESCRIPTION_NAME}: {error}"))?;

    Ok(written.len())
}

/// The hand-written Java sources, as they are kept in `java/`.
const HAND_WRITTEN: &[(&str, &str)] = &[
    (
        "ProtocolJson",
        include_str!("../../../java/ProtocolJson.java"),
    ),
    (
        "ProtocolViolation",
        include_str!("../../../java/ProtocolViolation.java"),
    ),
    ("AudioFrame", include_str!("../../../java/AudioFrame.java")),
];

const PACKAGE_PLACEHOLDER: &str = "package __PACKAGE__;";

/// A hand-written source with its package set and its repository path line
/// replaced: outside this repository that path names nothing.
fn in_package(source: &str, package: &str) -> Generated<String> {
    let (path_line, rest) = source
        .split_once('\n')
        .ok_or("a hand-written source is empty")?;
    if !path_line.starts_with("// java/") {
        return Err(format!(
            "a hand-written source does not start with its path: {path_line}"
        ));
    }
    if rest.matches(PACKAGE_PLACEHOLDER).count() != 1 {
        return Err(format!(
            "{path_line}: expected exactly one `{PACKAGE_PLACEHOLDER}`"
        ));
    }
    Ok(format!(
        "// Part of the Gabion node protocol library, written by hand in the controller's\n\
         // repository. Do not edit here.\n{}",
        rest.replace(PACKAGE_PLACEHOLDER, &format!("package {package};"))
    ))
}

fn write_file(directory: &Path, package: &str, name: &str, body: &str) -> Generated<()> {
    let mut text = String::new();
    let imports = [
        "com.fasterxml.jackson.annotation.JsonCreator",
        "com.fasterxml.jackson.annotation.JsonInclude",
        "com.fasterxml.jackson.annotation.JsonProperty",
        "com.fasterxml.jackson.annotation.JsonSubTypes",
        "com.fasterxml.jackson.annotation.JsonTypeInfo",
        "com.fasterxml.jackson.annotation.JsonValue",
        "java.util.List",
        "java.util.Objects",
        "org.jspecify.annotations.Nullable",
    ];
    emit(
        &mut text,
        format_args!(
            "// Generated from {DESCRIPTION_NAME} by protocol-java. Do not edit: change the\n\
         // protocol description and generate again.\n\
         package {package};\n"
        ),
    )?;
    for import in imports
        .iter()
        .filter(|import| body.contains(simple_name(import)))
    {
        emit(&mut text, format_args!("\nimport {import};"))?;
    }
    emit(&mut text, format_args!("\n\n{body}"))?;
    let path = directory.join(format!("{name}.java"));
    fs::write(&path, text).map_err(|error| format!("{}: {error}", path.display()))
}

fn simple_name(qualified: &str) -> &str {
    qualified.rsplit('.').next().unwrap_or(qualified)
}

fn emit(text: &mut String, arguments: std::fmt::Arguments<'_>) -> Generated<()> {
    text.write_fmt(arguments).map_err(|error| error.to_string())
}

/// The Java declaration of one definition.
fn declaration(name: &str, definition: &Value, package: &str) -> Generated<String> {
    let schema = definition.as_object().ok_or("is not an object")?;
    let doc = javadoc(schema, "");
    if let Some(alternatives) = schema.get("oneOf") {
        return union(name, &doc, alternatives, package);
    }
    match schema.get("type").and_then(Value::as_str) {
        Some("string") if schema.contains_key("enum") => enumeration(name, &doc, schema),
        Some("string") => Ok(format!(
            "{doc}public record {name}(@JsonValue String value) {{\n\n    \
             @JsonCreator(mode = JsonCreator.Mode.DELEGATING)\n    \
             public {name} {{\n        Objects.requireNonNull(value, \"value\");\n    }}\n}}\n"
        )),
        Some("object") => record(name, &doc, schema, None, "", package),
        other => Err(format!(
            "a definition of type {other:?} is not a form this generator knows"
        )),
    }
}

fn enumeration(name: &str, doc: &str, schema: &Map<String, Value>) -> Generated<String> {
    let values = schema
        .get("enum")
        .and_then(Value::as_array)
        .ok_or("enum is not a list")?;
    let mut text = format!("{doc}public enum {name} {{\n");
    for (index, value) in values.iter().enumerate() {
        let value = value.as_str().ok_or("an enum value is not a string")?;
        let separator = if index + 1 == values.len() { ";" } else { "," };
        emit(
            &mut text,
            format_args!(
                "    @JsonProperty(\"{value}\")\n    {}{separator}\n",
                value.to_uppercase()
            ),
        )?;
    }
    text.push_str("}\n");
    Ok(text)
}

fn union(name: &str, doc: &str, alternatives: &Value, package: &str) -> Generated<String> {
    let alternatives = alternatives.as_array().ok_or("oneOf is not a list")?;
    let mut subtypes = String::new();
    let mut records = String::new();
    for alternative in alternatives {
        let schema = alternative
            .as_object()
            .ok_or("an alternative is not an object")?;
        let tag = schema
            .get("properties")
            .and_then(|properties| properties.pointer("/type/const"))
            .and_then(Value::as_str)
            .ok_or(
                "an alternative has no `type` tag — only tagged alternatives are a known form",
            )?;
        let variant = pascal_case(tag);
        emit(
            &mut subtypes,
            format_args!(
                "    @JsonSubTypes.Type(value = {name}.{variant}.class, name = \"{tag}\"),\n"
            ),
        )?;
        let variant_doc = javadoc(schema, "    ");
        let body = record(&variant, &variant_doc, schema, Some(name), "    ", package)?;
        emit(&mut records, format_args!("\n{body}"))?;
    }
    Ok(format!(
        "{doc}@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = \"type\")\n\
         @JsonSubTypes({{\n{subtypes}}})\npublic sealed interface {name} {{\n{records}}}\n"
    ))
}

/// A record for an object rule; `parent` is the sealed interface it belongs to.
fn record(
    name: &str,
    doc: &str,
    schema: &Map<String, Value>,
    parent: Option<&str>,
    indent: &str,
    package: &str,
) -> Generated<String> {
    if schema.get("additionalProperties") != Some(&Value::Bool(false)) {
        return Err("an object that does not close its set of fields is not a known form".into());
    }
    let empty = Map::new();
    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .unwrap_or(&empty);
    let required: BTreeSet<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|names| names.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();

    let mut components = Vec::new();
    let mut checks = String::new();
    for (property, rule) in properties {
        // The tag of a tagged alternative is carried by the type itself.
        if parent.is_some() && property == "type" {
            continue;
        }
        // Inside a sealed interface a sibling record can carry the name of a
        // top-level type — `ControllerMessage.Event` beside `Event` — and
        // would be taken for it. There the referenced types are named in
        // full, so a field can only ever mean the type the description means.
        let qualifier = parent.map(|_| package);
        let field = camel_case(property);
        if JAVA_RESERVED.contains(&field.as_str()) {
            return Err(format!(
                "field `{property}` would be a reserved word in Java"
            ));
        }
        let java_type = java_type(rule, qualifier)
            .map_err(|problem| format!("field `{property}`: {problem}"))?;
        if required.contains(property.as_str()) {
            if java_type.starts_with("List<") {
                emit(
                    &mut checks,
                    format_args!("{indent}        {field} = List.copyOf({field});\n"),
                )?;
            } else if java_type != "long" {
                emit(
                    &mut checks,
                    format_args!("{indent}        Objects.requireNonNull({field}, \"{field}\");\n"),
                )?;
            }
            components.push(format!("@JsonProperty(\"{property}\") {java_type} {field}"));
        } else {
            components.push(format!(
                "@JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty(\"{property}\") {} {field}",
                nullable(&boxed(&java_type))
            ));
        }
    }

    let modifier = if parent.is_some() { "" } else { "public " };
    let implements = parent
        .map(|parent| format!(" implements {parent}"))
        .unwrap_or_default();
    let separator = format!(",\n{indent}        ");
    let list = if components.is_empty() {
        String::new()
    } else {
        format!("\n{indent}        {}", components.join(&separator))
    };
    let body = if checks.is_empty() {
        String::new()
    } else {
        // A record nested in an interface is public whether it says so or
        // not, and its constructor may not be less accessible than itself.
        format!("\n{indent}    public {name} {{\n{checks}{indent}    }}\n{indent}")
    };
    Ok(format!(
        "{doc}{indent}{modifier}record {name}({list}){implements} {{{body}}}\n"
    ))
}

fn java_type(rule: &Value, qualifier: Option<&str>) -> Generated<String> {
    let rule = rule.as_object().ok_or("its rule is not an object")?;
    if let Some(reference) = rule.get("$ref").and_then(Value::as_str) {
        return reference
            .strip_prefix("#/definitions/")
            .map(|name| match qualifier {
                Some(package) => format!("{package}.{name}"),
                None => name.to_owned(),
            })
            .ok_or_else(|| format!("reference {reference} is not to a definition"));
    }
    match rule.get("type").and_then(Value::as_str) {
        Some("string") if !rule.contains_key("enum") => Ok("String".into()),
        Some("integer") => Ok("long".into()),
        Some("array") => {
            let items = rule
                .get("items")
                .ok_or("a list does not say what it holds")?;
            Ok(format!("List<{}>", boxed(&java_type(items, qualifier)?)))
        }
        other => Err(format!(
            "a field of type {other:?} is not a form this generator knows"
        )),
    }
}

/// A type marked as possibly absent. The mark is a type-use annotation, so
/// on a type named in full it goes before the simple name, not before the
/// package.
fn nullable(java_type: &str) -> String {
    match java_type.rsplit_once('.') {
        Some((package, name)) if !java_type.contains('<') => format!("{package}.@Nullable {name}"),
        _ => format!("@Nullable {java_type}"),
    }
}

fn boxed(java_type: &str) -> String {
    if java_type == "long" {
        "Long".into()
    } else {
        java_type.into()
    }
}

fn javadoc(schema: &Map<String, Value>, indent: &str) -> String {
    schema
        .get("description")
        .and_then(Value::as_str)
        .map(|text| {
            let safe = text
                .replace("*/", "*&#47;")
                .replace('&', "&amp;")
                .replace('<', "&lt;");
            format!("{indent}/** {safe} */\n")
        })
        .unwrap_or_default()
}

fn pascal_case(snake: &str) -> String {
    snake
        .split('_')
        .map(|word| {
            let mut letters = word.chars();
            letters
                .next()
                .map(|first| first.to_uppercase().chain(letters).collect::<String>())
                .unwrap_or_default()
        })
        .collect()
}

fn camel_case(snake: &str) -> String {
    let pascal = pascal_case(snake);
    let mut letters = pascal.chars();
    letters
        .next()
        .map(|first| first.to_lowercase().chain(letters).collect())
        .unwrap_or_default()
}
